permalink: pretty
exclude: [node_modules]
keep_files: [assets/css, archive]
name: Machine Conf
description: Introducing GopherCon UK, formerly known as the Golang UK Conference. Join us for three days of great Go content with the best speakers from across the world.
collections:
  videos:
    output: true
    permalink: /videos/:path/
    title: Videos

defaults:
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
  - scope:
      path: _videos/2016
    values:
      year: "2016"
  - scope:
      path: _videos/2015
    values:
      year: "2015"
